services:
  nextjs:
    build:
      context: .
      dockerfile: apps/nextjs/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEST_INTERNAL_URL=http://nestjs:3001
      - HOST_MACHINE_NAME=local-compose
    depends_on:
      - nestjs
  nestjs:
    build:
      context: .
      dockerfile: apps/nestjs/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - HOST_MACHINE_NAME=local-compose
